[package]
name = "disjoint_impls"
version = "0.7.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mversic/disjoint_impls"
description = "Support for mutually disjoint impls"
keywords = ["disjoint", "exclusive", "associated", "impl", "implementation"]

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0.48", features = ["full", "extra-traits", "visit", "visit-mut"]}
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.78"
itertools = "0.12.1"
indexmap = "2.2.5"
quote = "1.0.35"
